// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/help": {
    params: {};
  };
  "/business": {
    params: {};
  };
  "/business-management": {
    params: {};
  };
  "/deal-details/:id": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/business-registration": {
    params: {};
  };
  "/customer-registration": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/help" | "/business" | "/business-management" | "/deal-details/:id" | "/login" | "/profile" | "/business-registration" | "/customer-registration" | "/verify-email" | "/*";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/help.tsx": {
    id: "routes/help";
    page: "/help";
  };
  "./routes/business-info.tsx": {
    id: "routes/business-info";
    page: "/business";
  };
  "./routes/business-management.tsx": {
    id: "routes/business-management";
    page: "/business-management";
  };
  "./routes/deal-details.$id.tsx": {
    id: "routes/deal-details.$id";
    page: "/deal-details/:id";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "./routes/business-registration.tsx": {
    id: "routes/business-registration";
    page: "/business-registration";
  };
  "./routes/customer-registration.tsx": {
    id: "routes/customer-registration";
    page: "/customer-registration";
  };
  "./routes/customer-registration-validate.tsx": {
    id: "routes/customer-registration-validate";
    page: "/verify-email";
  };
  "./routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "routes/help": typeof import("./app/./routes/help.tsx");
  "routes/business-info": typeof import("./app/./routes/business-info.tsx");
  "routes/business-management": typeof import("./app/./routes/business-management.tsx");
  "routes/deal-details.$id": typeof import("./app/./routes/deal-details.$id.tsx");
  "routes/login": typeof import("./app/./routes/login.tsx");
  "routes/profile": typeof import("./app/./routes/profile.tsx");
  "routes/business-registration": typeof import("./app/./routes/business-registration.tsx");
  "routes/customer-registration": typeof import("./app/./routes/customer-registration.tsx");
  "routes/customer-registration-validate": typeof import("./app/routes/customer-verify-email.js");
  "routes/404": typeof import("./app/./routes/404.tsx");
};